apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-postgres-pvc
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi