# Default values for todo-chatbot
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 1
  image:
    repository: phase3-backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

frontend:
  replicaCount: 1
  image:
    repository: phase3-frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: NodePort
    port: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

postgres:
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Database and API configuration
secrets:
  databaseUrl: ""
  openaiApiKey: ""